/*
 * generated by Xtext 2.25.0
 */
package de.itemis.tooling.terminology.ide;

import org.eclipse.xtext.util.Modules2;

import com.google.inject.Guice;
import com.google.inject.Injector;

import de.itemis.tooling.terminology.TerminologyRuntimeModule;
import de.itemis.tooling.terminology.TerminologyStandaloneSetup;

/**
 * Initialization support for running Xtext languages as language servers.
 */
public class TerminologyIdeSetup extends TerminologyStandaloneSetup {

	@Override
	public Injector createInjector() {
		return Guice.createInjector(Modules2.mixin(new TerminologyRuntimeModule(), new TerminologyIdeModule()));
	}
	
}
