/*
 * generated by Xtext 2.25.0
 */
package de.itemis.tooling.terminology.ide;


/**
 * Use this class to register ide components.
 */
public class TerminologyIdeModule extends AbstractTerminologyIdeModule {
}
