/*
 * generated by Xtext
 */
package de.itemis.tooling.terminology.generator

import org.eclipse.emf.ecore.resource.Resource
import org.eclipse.xtext.generator.IFileSystemAccess
import org.eclipse.xtext.generator.IGenerator

class TerminologyGenerator implements IGenerator {
	
	override void doGenerate(Resource resource, IFileSystemAccess fsa) {
		//exists, so that there are no compile errors
//		resource.contents.get(0).createFiles(fsa)
	}
}
