/*
* generated by Xtext
*/
package de.itemis.tooling.terminology.ui.contentassist;

import de.itemis.tooling.terminology.ui.contentassist.AbstractTerminologyProposalProvider;
/**
 * see http://www.eclipse.org/Xtext/documentation/latest/xtext.html#contentAssist on how to customize content assistant
 */
public class TerminologyProposalProvider extends AbstractTerminologyProposalProvider {

}
