/*
* generated by Xtext
*/
package de.itemis.tooling.terminology.ui.labeling;

import org.eclipse.xtext.resource.IEObjectDescription;
import org.eclipse.xtext.ui.label.DefaultDescriptionLabelProvider;

import de.itemis.tooling.terminology.terminology.TerminologyPackage;

/**
 * Provides labels for a IEObjectDescriptions and IResourceDescriptions.
 * 
 * see http://www.eclipse.org/Xtext/documentation/latest/xtext.html#labelProvider
 */
public class TerminologyDescriptionLabelProvider extends DefaultDescriptionLabelProvider {

/*
	//Labels and icons can be computed like this:
	
	String text(IEObjectDescription ele) {
	  return "my "+ele.getName();
	}
	 
    String image(IEObjectDescription ele) {
      return ele.getEClass().getName() + ".gif";
    }	 
*/
	@Override
	public String text(IEObjectDescription ele) {
		if(ele.getEClass()==TerminologyPackage.Literals.TERM){
			return ele.getName().getLastSegment()+ " - Term";
		}
		return (String)super.text(ele);
	}

	public String image(IEObjectDescription ele) {
		if(ele.getEClass()==TerminologyPackage.Literals.TERM){
			if("preferred".equals(ele.getUserData("status"))){
				return "preferredterm.png";
			}else{
				return "term.png";
			}
		}
		return (String)super.image(ele);
	}
}
