/*
* generated by Xtext
*/
package de.itemis.tooling.terminology.ui.labeling;

import org.eclipse.emf.edit.ui.provider.AdapterFactoryLabelProvider;
import org.eclipse.xtext.ui.label.DefaultEObjectLabelProvider;

import com.google.inject.Inject;

import de.itemis.tooling.terminology.terminology.Term;

/**
 * Provides labels for a EObjects.
 * 
 * see http://www.eclipse.org/Xtext/documentation/latest/xtext.html#labelProvider
 */
public class TerminologyLabelProvider extends DefaultEObjectLabelProvider {

	@Inject
	public TerminologyLabelProvider(AdapterFactoryLabelProvider delegate) {
		super(delegate);
	}

/*
	//Labels and icons can be computed like this:
	
	String text(MyModel ele) {
	  return "my "+ele.getName();
	}
	 
    String image(MyModel ele) {
      return "MyModel.gif";
    }
*/
	public String image(Term term) {
		String result=null;
		switch(term.getStatus()){
			case PREFERRED:result="public_co.gif";break;
			case PERMITTED:result="protected_co.gif";break;
			case REJECTED:result="private_co.gif";break;
			case SUPERSEDED:result="compare_method.gif";break;
		}
		return result;
	}
}
